const RES_DATA = [
  {
    id: 1,
    name: "Spice Garden",
    cuisine: "Indian",
    rating: 4.5,
    eta: "30 mins",
    location: "Downtown",
    price_range: "$$",
  },
  {
    id: 2,
    name: "Pasta Palace",
    cuisine: "Italian",
    rating: 4.2,
    eta: "25 mins",
    location: "City Center",
    price_range: "$$",
  },
  {
    id: 3,
    name: "Sushi World",
    cuisine: "Japanese",
    rating: 4.8,
    eta: "40 mins",
    location: "Uptown",
    price_range: "$$$",
  },
  {
    id: 4,
    name: "Burger Hub",
    cuisine: "American",
    rating: 4.0,
    eta: "20 mins",
    location: "Midtown",
    price_range: "$",
  },
  {
    id: 5,
    name: "Curry Express",
    cuisine: "Indian",
    rating: 4.3,
    eta: "35 mins",
    location: "East Side",
    price_range: "$$",
  },
  {
    id: 6,
    name: "Taco Fiesta",
    cuisine: "Mexican",
    rating: 4.1,
    eta: "22 mins",
    location: "City Center",
    price_range: "$",
  },
  {
    id: 7,
    name: "Dragon Bowl",
    cuisine: "Chinese",
    rating: 4.4,
    eta: "30 mins",
    location: "Downtown",
    price_range: "$$",
  },
  {
    id: 8,
    name: "The Greek House",
    cuisine: "Greek",
    rating: 4.6,
    eta: "28 mins",
    location: "Old Town",
    price_range: "$$",
  },
  {
    id: 9,
    name: "Pizza Time",
    cuisine: "Italian",
    rating: 4.0,
    eta: "18 mins",
    location: "West End",
    price_range: "$",
  },
  {
    id: 10,
    name: "Veggie Delight",
    cuisine: "Vegan",
    rating: 4.7,
    eta: "32 mins",
    location: "Uptown",
    price_range: "$$",
  },
  {
    id: 11,
    name: "BBQ Brothers",
    cuisine: "American BBQ",
    rating: 4.5,
    eta: "27 mins",
    location: "South Side",
    price_range: "$$$",
  },
  {
    id: 12,
    name: "Ramen Stop",
    cuisine: "Japanese",
    rating: 4.3,
    eta: "24 mins",
    location: "Midtown",
    price_range: "$$",
  },
  {
    id: 13,
    name: "Kebab King",
    cuisine: "Middle Eastern",
    rating: 4.2,
    eta: "30 mins",
    location: "Downtown",
    price_range: "$$",
  },
  {
    id: 14,
    name: "French Cravings",
    cuisine: "French",
    rating: 4.6,
    eta: "45 mins",
    location: "City Center",
    price_range: "$$$",
  },
  {
    id: 15,
    name: "Smoothie Spot",
    cuisine: "Healthy & Smoothies",
    rating: 4.4,
    eta: "15 mins",
    location: "East Side",
    price_range: "$",
  },
];

export default RES_DATA;
